# Generated by Django 3.1.7 on 2021-11-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='time_submitted',
            new_name='submitted_at',
        ),
    ]
